-- MySQL Script generated by MySQL Workbench
-- Wed May 15 00:02:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web` DEFAULT CHARACTER SET utf8 ;
USE `web` ;

-- -----------------------------------------------------
-- Table `web`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`movies` ;

CREATE TABLE IF NOT EXISTS `web`.`movies` (
  `id` INT NOT NULL,
  `name` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `lens_id` VARCHAR(10) NULL,
  `cover` VARCHAR(128) NULL,
  `duration` INT NULL,
  `year` INT NULL,
  `imdb` VARCHAR(20) NULL,
  `summary` VARCHAR(600) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `genres` VARCHAR(90) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT 'concat the genre with ‘ , ’',
  `pubdate` VARCHAR(45) NULL,
  `countries` VARCHAR(270) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT 'concat the genre with ‘ , ’',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web`.`director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`director` ;

CREATE TABLE IF NOT EXISTS `web`.`director` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web`.`cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`cast` ;

CREATE TABLE IF NOT EXISTS `web`.`cast` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`rating` ;

CREATE TABLE IF NOT EXISTS `web`.`rating` (
  `average` DOUBLE NULL,
  `rating_people` INT NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`movies_id`),
  CONSTRAINT `fk_rating_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `web`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`movies_has_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`movies_has_cast` ;

CREATE TABLE IF NOT EXISTS `web`.`movies_has_cast` (
  `movies_id` INT NOT NULL,
  `cast_id` INT NOT NULL,
  PRIMARY KEY (`movies_id`, `cast_id`),
  INDEX `fk_movies_has_cast_cast1_idx` (`cast_id` ASC),
  INDEX `fk_movies_has_cast_movies_idx` (`movies_id` ASC),
  CONSTRAINT `fk_movies_has_cast_movies`
    FOREIGN KEY (`movies_id`)
    REFERENCES `web`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_cast_cast1`
    FOREIGN KEY (`cast_id`)
    REFERENCES `web`.`cast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web`.`movies_has_director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`movies_has_director` ;

CREATE TABLE IF NOT EXISTS `web`.`movies_has_director` (
  `movies_id` INT NOT NULL,
  `director_id` INT NOT NULL,
  PRIMARY KEY (`movies_id`, `director_id`),
  INDEX `fk_movies_has_director_director1_idx` (`director_id` ASC),
  INDEX `fk_movies_has_director_movies1_idx` (`movies_id` ASC),
  CONSTRAINT `fk_movies_has_director_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `web`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_director_director1`
    FOREIGN KEY (`director_id`)
    REFERENCES `web`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web`.`writers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`writers` ;

CREATE TABLE IF NOT EXISTS `web`.`writers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`movies_has_writers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web`.`movies_has_writers` ;

CREATE TABLE IF NOT EXISTS `web`.`movies_has_writers` (
  `movies_id` INT NOT NULL,
  `writers_id` INT NOT NULL,
  PRIMARY KEY (`movies_id`, `writers_id`),
  INDEX `fk_movies_has_writers_writers1_idx` (`writers_id` ASC),
  INDEX `fk_movies_has_writers_movies1_idx` (`movies_id` ASC),
  CONSTRAINT `fk_movies_has_writers_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `web`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_writers_writers1`
    FOREIGN KEY (`writers_id`)
    REFERENCES `web`.`writers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
